# Generated by Django 3.1.6 on 2021-02-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('miniature', models.FileField(upload_to='')),
                ('expiry_date', models.CharField(max_length=120)),
                ('steps', models.TextField()),
            ],
        ),
    ]
