# Generated by Django 3.1.6 on 2021-02-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.TextField()),
                ('text', models.CharField(max_length=120)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('text', models.CharField(max_length=120)),
                ('miniature', models.FileField(upload_to='')),
                ('link', models.TextField()),
                ('service_id', models.TextField()),
                ('task', models.TextField()),
                ('about_company', models.TextField()),
            ],
        ),
    ]
