# Generated by Django 3.1.6 on 2021-02-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gallery_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('avatar', models.FileField(upload_to='')),
                ('skills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('price', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=120)),
                ('task', models.TextField()),
                ('is_new', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('contacts', models.TextField()),
                ('service', models.TextField()),
                ('project', models.TextField()),
                ('main', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
