# Generated by Django 3.1.6 on 2021-02-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210214_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
