# Generated by Django 3.1.6 on 2021-02-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210217_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.project'),
        ),
    ]
