# Generated by Django 3.1.6 on 2021-02-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210217_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='steps',
        ),
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together={('project_id',)},
        ),
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.service')),
            ],
        ),
    ]
