# Generated by Django 3.1.6 on 2021-02-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210217_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestep',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.service'),
        ),
    ]
